title: devlopr
subtitle: A Jekyll Theme Built For Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide

# Edit these details 

author_logo: profile.png
author: John Doe
author_bio: Hi, My Name is John Doe. I love to Code and Design. devlopr-jekyll is a theme built for developers.  
author_email: "leetxor@gmail.com"
author_location: India
author_website_url: "http://leetxor.com"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
twitter_username: leetxor
github_username:  leetxor
facebook_username: leetxor
linkedin_username: leetxor
behance_username: leetxor
instagram_username: leetxor
medium_username: leetxor
telegram_username: leetxor
dribbble_username: leetxor
flickr_username: leetxor

#for comments using disqus
disqus_shortname: leetxor-github-io  

# wakatime username (coding activity)
wakatime_username: leetxor

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


